import Menu from './menu.png'
import Localidade from './localidade.png'
import Projeto from './projeto.png'
import Github from './github.png'
import Instagram from './instagram.png'
import Linkedin from './linkedin.png'
import Twitter from './twitter.png'
import EuBarra from './eubarra.jpg'
import Carro from './eucarro.jpg'
import Futebol from './futebol.jpg'
import Foto from './fotorio.jpg'
import Barra from './riobarra.jpg'
import Eu from './eu.jpg'
import Agua from './agua.jpg'
import Balsa from './balsa.jpg'
import Barcos from './barcos.jpg'
import Cachorro from './cachorro.jpg'
import Cb from './cb.jpg'
import Ceu from './ceu.jpg'
import Cocos from './cocos.jpg'
import Eunapolis from './eunapolis.jpg'
import Gato from './gato.jpg'
import Nuvem from './nuvem.jpg'
import Onda from './onda.jpg'
import Pedras from './pedras.jpg'
import Pier from './pier.jpg'
import Rio from './rio.jpg'
import Sa from './sa.jpg'
import Sol from './sol.jpg'
import Veleiro from './veleiro.jpg'
import Praia from './praia.jpg'

export {
    Menu, Localidade, Projeto, Github, Instagram, Linkedin, Twitter, EuBarra, Carro, Foto, Barra, Eu, Futebol, Praia, Agua, Balsa, Barcos, Cachorro, Cb, Ceu, Cocos, Eunapolis, Gato, Nuvem, Onda, Pedras, Pier, Rio, Sa, Sol, Veleiro 
    }